### ISSUE TITLE
Why GPL?

### ISSUE THREAD

**Issue by zalo** [pca006132/sscad#5]
If this is an independent implementation, it shouldn’t be constrained by OpenSCAD’s original license… and it would probably be included in more projects with a less invasive license.

For instance, I think it would be a fun frontend for CascadeStudio: https://github.com/zalo/CascadeStudio

**Comment by pca006132** [comment]
I am not entirely sure if my parser is not a "derived work" of OpenSCAD's parser, considering I have read their source code and the implementation of parsers are very similar anyway. @kintel is thinking about re-licensing their parser into a more permissive license, and I can change this license to something like Apache 2.0 at that point.

This may be too pedantic though, I don't think anyone will come here to say things about violating GPL, but just to play safe...

**Comment by pca006132** [comment]
It seems that the core devs of openscad think that the implementation here is very different from the one in openscad. I will change the license to Apache 2.0 tonight.

**Comment by zalo** [comment]
Does it make sense to put it in as a submodule in manifold (as a file import format)?

Might be a universe where it makes sense to have a Manifold constructor that takes in a SCAD string…

(Or, perhaps an array of tuples representing the file contents and paths of each contributing .scad file)

**Comment by pca006132** [comment]
I think this should be a dependency of the final CAD package instead of a dependency of manifold, e.g. dependency of manifoldcad or openscad. The way this is designed decouples the interpreter from the underlying geometry library, so the CAD package can choose which backend to use, perhaps even dynamically. I think this is the most flexible design.
And I don't really care about the actual file format here, as long as the user of sscad give me some path to file ID mapping and file ID to input stream mapping. The input stream can be from a file, fetched from the internet or just some strings. I does not matter.
